### ISSUE TITLE
50 nuget packages

### ISSUE THREAD

**Issue by ddecroos** [PitneyBowes/pitneybowes-shipping-api-csharp#12]
Hi

I started using the SDK a few days ago, and I'm really annoyed by the fact that this nuget has 50 nuget dependencies, most of them being part of .Net framework (System.IO, System.Linq, System.Reflection, ...).
Is there a way to get a version that only include necessary nugets (like Newtonsoft)?

Thanks
![2018-06-22_15h04_19](https://user-images.githubusercontent.com/40440777/41797256-f57b4718-762e-11e8-9898-242f576b638a.png)

**Comment by paddypawprints** [comment]
Hi,

There are only 3 first level dependencies in the project.

![image](https://user-images.githubusercontent.com/21299031/41800195-632d361e-7629-11e8-9ad9-caca89583746.png)

All of the others show up due to the way Microsoft has chosen to package .net standard. Which platform/runtime are you working on?

**Comment by ddecroos** [comment]
Hi

thanks for your response.
I'm using Visual Studio 2017 on Win10

**Comment by paddypawprints** [comment]
Which .net framework version are you using?

I realized I had read this article at some point. It explains why there are so many dependencies. 

https://stackoverflow.com/questions/47365136/why-does-my-net-standard-nuget-package-trigger-so-many-dependencies

We made the choice to target .net Standard 1.3 so we could cover the largest possible set of target frameworks (given the functionality). Looking at the compatibility matrix it seems as though the difference is support for .net framework 4.6 vs. 4.6.1. We should probably give some thought to how relevant that is.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by ddecroos** [comment]
Sorry, I didn't have time to get back to you yet
I'm targeting Framework 4.6.
What you're saying is that it should pull all the 50 dependencies only if I targeted a version lower than 4.6, or is it the other way around?

**Comment by paddypawprints** [comment]
The dependencies are a result of us using dontnet standard 1.3 and the way Microsoft chose to package the framework in that version. Per the articles above it wont result in any runtime or bloat issues, but I agree it is pretty ugly. If we were to upgrade to dotnet standard 2.0, then we could not support framework 4.6.

To use the nuget package you will need to get all of the dependencies. Alternative would be to get the sdk source code and build it targeting .net framework.
