### ISSUE TITLE
Add rates and shipment parameter includeDeliveryCommitment

### ISSUE THREAD

**Issue by paddypawprints** [PitneyBowes/pitneybowes-shipping-api-csharp#13]
Per PB documentation this is a boolean and shows up in the query parameters of the request. 

e.g. 
curl -X POST .../v1/rates?includeDeliveryCommitment=false

**Comment by pa009fa** [comment]
Fixed in nuget package 1.0.12

Parameter added to Shipment class for CreateShipment and Rate methods.
