### ISSUE TITLE
Should be able to enter a blank serviceId for Rate shopping 

### ISSUE THREAD

**Issue by pobering** [PitneyBowes/pitneybowes-shipping-api-csharp#14]
Should allow the user to leave the serviceId blank to receive an array containing quoted rates for each of the valid serviceId types in one response.

**Comment by pa009fa** [comment]
Fixed in nuget package 1.0.12

Field can be left blank.

Added new fluent methods:
- RateShopService()
- RateShopParcelType()

e.g.                     .Rates(RatesArrayFluent<Rates>.Create().RateShopService()
