### ISSUE TITLE
Create Shipping Label for USPS First Class Mail Flat Envelope

### ISSUE THREAD

**Issue by bravemav** [PitneyBowes/pitneybowes-shipping-api-csharp#17]
I've been able to run the sample program fine without any problems. The shipping label was retrieved and saved successfully as a PDF.

However, once I try creating a shipping label for a first class mail flat envelope, I get an error.

Here is the snippet of code I changed from the sample program:

`.Rates(RatesArrayFluent<Rates>.Create().Add().Carrier(Carrier.USPS).Service(Services.FCM).ParcelType(ParcelType.FLAT))`

And here is the errors I receive when submitting the request:

> 1050001
Invalid label paper size

> 1050002
Invalid label receipt option for given paper size

> 1050001
Invalid label paper size

> 1059999
A system error occurred, try again later. If the error persists, please contact the service provider.

What am I missing here?  What Can I do to get this to generate the shipping label correctly?

Again, the lines above are the only things I changed from the sample program.

**Comment by pa009fa** [comment]
Hi,

Are you on Windows? Do you have a Fiddler log of what is being sent to the server?

Thanks

**Comment by pa009fa** [comment]
I reproduced the error - getting help from the shipping API support team.

**Comment by pa009fa** [comment]
Fixed in latest Nuget package 1.0.12. 

Use document size DOC_6X4 rather than DOC_4X6 (this parameter will be available when you update the nuget package.
