### ISSUE TITLE
Needs cast to Dictionary<string,string>

### ISSUE THREAD

**Issue by holisticturtle** [PitneyBowes/pitneybowes-shipping-api-csharp#18]
https://github.com/PitneyBowes/pitneybowes-shipping-api-csharp/blob/7038f9bbb9f8e07924c72e39988dc0f8d1d53902/examples/example/Program.cs#L432

**Comment by paddypawprints** [comment]
Thanks. Could you send a pull request? Let me know if it's a hassle.

**Comment by pa009fa** [comment]
Reworked the configuration for the latest upgrade. Fixes this and other problems.
