### ISSUE TITLE
MyShip Example not working

### ISSUE THREAD

**Issue by owensearls** [PitneyBowes/pitneybowes-shipping-api-csharp#27]
I am using .NET Core 2.2, and installed version 1.1.0 of the shippingapi package. When I copy the sample program, it initially fails to build, telling me that the "PBPresortShipment" and "PBPresortPermit" methods do not exist. I deleted those two lines, and then got runtime errors saying that a number of Config strings were not found. I added them in like so

sandbox.AddConfigItem("Retries", "1");
sandbox.AddConfigItem("ThrowExceptions", "true");
sandbox.AddConfigItem("RecordRoot", "true");
sandbox.AddConfigItem("RecordAPICalls", "true");

With this combination of config options I am getting a NullReferenceException in the fluent API creating the Shipment object. I also tried with retries set to 0, and got a PitneyBowes.Developer.ShippingApi.ShippingAPIException. I played with the values of the other three config options, but didn't see anything change. I set up logging as shown in your other example, but didn't get any new information.

**Comment by pa009fa** [comment]
Got it working again. Checked in PB Presort testing by mistake.
