### ISSUE TITLE
Does this SDK work at all?

### ISSUE THREAD

**Issue by mattglet** [PitneyBowes/pitneybowes-shipping-api-csharp#31]
I'm getting these errors from my code:
* shipment.rates[0].carrier: must not be null
* shipment.rates[0].carrier: must not be blank
* shipment.parcel.weight: must not be null

How can Carrier and Weight be reported as null in this scenario?

```
var shipment = (Shipment)ShipmentFluent<Shipment>.Create()
	.FromAddress((Address)AddressFluent<Address>.Create()
		.PostalCode(fromZip)
		.CountryCode(fromCountryIso2))
	.ToAddress((Address)AddressFluent<Address>.Create()
		.PostalCode(toZip)
		.CountryCode(toCountryIso2));

var parcel = new Parcel
{
	Weight = new ParcelWeight { Weight = Convert.ToDecimal(weightOz), UnitOfMeasurement = UnitOfWeight.OZ }
};

var rate = new Rates
{
	Carrier = Carrier.USPS,
	ServiceId = Services.FCM,
	ParcelType = ParcelType.PKG
};

shipment.Parcel = parcel;
shipment.AddRates(rate);

var ratesResponse = Api.Rates(shipment).GetAwaiter().GetResult();
```

**Comment by am005si** [comment]
Hi Matt,

The Rates Carrier and Parcel Weights are mandatory fields and cannot be null.

Following is examples for using SDK

https://github.com/PitneyBowes/pitneybowes-shipping-api-csharp/blob/master/examples/example/Program.cs


The API’s used in back of SDKs to create shipment is as follows:

https://shipping.pitneybowes.com/api/post-shipments.html


Regards
Amit

**Comment by mattglet** [comment]
Hello Amit, thanks for the reply.

However, in my code above, I am populating the Rate Carrier and the Parcel Weight. But the error I'm receiving is that they are both null/blank.

**Comment by am005si** [comment]
Hi Matt,



Please try following sample


`var shipment = ShipmentFluent<Shipment>.Create()
                    .ToAddress((Address)AddressFluent<Address>.Create()
                        .AddressLines("643 Greenway RD")
                        .PostalCode("28607")
                        .CountryCode("US")
                        .Verify() // calls the service for address validation - will populate city and state from the zip
                        )
                    .MinimalAddressValidation("true")
                    //.ShipperRatePlan(Globals.DefaultSession.GetConfigItem("RatePlan")) // use if you have a custom rate plan
                    .FromAddress((Address)AddressFluent<Address>.Create()
                        .Company("Pitney Bowes Inc.")
                        .AddressLines("27 Waterview Drive")
                        .Residential(false)
                        .CityTown("Shelton")
                        .StateProvince("CT")
                        .PostalCode("06484")
                        .CountryCode("US")
                        .Person("Paul Wright", "203-555-1213", "john.publica@pb.com")
                        )
                    .Parcel((Parcel)ParcelFluent<Parcel>.Create()
                        .Dimension(12, 12, 10)
                        .Weight(16m, UnitOfWeight.OZ)
                        )
                    .Rates(RatesArrayFluent<Rates>.Create()
                        .USPSPriority<Rates, Parameter>()
                        .InductionPostalCode("06484")
                        )
                    .Documents((List<IDocument>)DocumentsArrayFluent<Document>.Create()
                        .ShippingLabel(ContentType.BASE64, Size.DOC_4X6, FileFormat.ZPL2)
                        )
                    .ShipmentOptions(ShipmentOptionsArrayFluent<ShipmentOptions>.Create()
                        .ShipperId(sandbox.GetConfigItem("ShipperID"))
                        .AddToManifest()
                        )
                    .TransactionId(Guid.NewGuid().ToString().Substring(15));


                var label = Api.CreateShipment((Shipment)shipment).GetAwaiter().GetResult();`

Regards
Amit

**Comment by mattglet** [comment]
Thank you Amit. It turns out I was missing this which is vital to the execution of the call.:
`Model.RegisterSerializationTypes(session.SerializationRegistry);`

I've added it and things seem to be working now.
