### ISSUE TITLE
AccountBalanceRequest - incorrect property name

### ISSUE THREAD

**Issue by mattglet** [PitneyBowes/pitneybowes-shipping-api-csharp#32]
The URL to retrieve Account Balance expects `{AccountId}` as a replacement property: 
https://github.com/PitneyBowes/pitneybowes-shipping-api-csharp/blob/master/src/method/Merchant.cs#L516

However the AccountBalanceRequest object does not have that property, instead it has `AccountNumber`

**Comment by am005si** [comment]
Hi ,

We are working towards analyzing it .

If we need to put a fix we will do a release.

Regards
Amit

**Comment by NEX7FDK** [comment]
We have fixed  this issue from our end and check in  Github and we  will release in C# SDK  very soon

**Comment by am005si** [comment]
This Bug has been fixed and part of new release 1.2.0
